export type CoinCategory = "popular" | "more";

export type Coin = {
  symbol: string;
  name: string;
  category: CoinCategory;
};

// "popular" — well-known, top-of-mind coins.
// "more" — real, established coins most casual visitors won't recognize by
// name, grouped separately so the popular list stays uncluttered.
export const COINS: Coin[] = [
  { symbol: "BTC", name: "Bitcoin", category: "popular" },
  { symbol: "ETH", name: "Ethereum", category: "popular" },
  { symbol: "SOL", name: "Solana", category: "popular" },
  { symbol: "XRP", name: "XRP", category: "popular" },
  { symbol: "ADA", name: "Cardano", category: "popular" },
  { symbol: "DOGE", name: "Dogecoin", category: "popular" },
  { symbol: "AVAX", name: "Avalanche", category: "popular" },
  { symbol: "LINK", name: "Chainlink", category: "popular" },
  { symbol: "LTC", name: "Litecoin", category: "popular" },
  { symbol: "DOT", name: "Polkadot", category: "popular" },
  { symbol: "BCH", name: "Bitcoin Cash", category: "popular" },
  { symbol: "UNI", name: "Uniswap", category: "popular" },
  { symbol: "ATOM", name: "Cosmos", category: "popular" },
  { symbol: "ETC", name: "Ethereum Classic", category: "popular" },
  { symbol: "FIL", name: "Filecoin", category: "popular" },
  { symbol: "NEAR", name: "NEAR Protocol", category: "popular" },
  { symbol: "SUI", name: "Sui", category: "popular" },

  { symbol: "MATIC", name: "Polygon", category: "more" },
  { symbol: "ARB", name: "Arbitrum", category: "more" },
  { symbol: "OP", name: "Optimism", category: "more" },
  { symbol: "SEI", name: "Sei", category: "more" },
  { symbol: "INJ", name: "Injective", category: "more" },
  { symbol: "RNDR", name: "Render", category: "more" },
  { symbol: "TIA", name: "Celestia", category: "more" },
  { symbol: "FTM", name: "Fantom", category: "more" },
  { symbol: "ALGO", name: "Algorand", category: "more" },
  { symbol: "VET", name: "VeChain", category: "more" },
  { symbol: "ICP", name: "Internet Computer", category: "more" },
  { symbol: "HBAR", name: "Hedera", category: "more" },
  { symbol: "THETA", name: "Theta Network", category: "more" },
  { symbol: "XLM", name: "Stellar", category: "more" },
  { symbol: "XTZ", name: "Tezos", category: "more" },
  { symbol: "EOS", name: "EOS", category: "more" },
  { symbol: "EGLD", name: "MultiversX", category: "more" },
  { symbol: "SAND", name: "The Sandbox", category: "more" },
  { symbol: "MANA", name: "Decentraland", category: "more" },
  { symbol: "AXS", name: "Axie Infinity", category: "more" },
  { symbol: "GALA", name: "Gala", category: "more" },
  { symbol: "CHZ", name: "Chiliz", category: "more" },
  { symbol: "ENJ", name: "Enjin Coin", category: "more" },
  { symbol: "GRT", name: "The Graph", category: "more" },
  { symbol: "IMX", name: "Immutable", category: "more" },
  { symbol: "RUNE", name: "THORChain", category: "more" },
  { symbol: "KAVA", name: "Kava", category: "more" },
  { symbol: "ZEC", name: "Zcash", category: "more" },
  { symbol: "DASH", name: "Dash", category: "more" },
  { symbol: "CAKE", name: "PancakeSwap", category: "more" },
  { symbol: "SUSHI", name: "SushiSwap", category: "more" },
  { symbol: "COMP", name: "Compound", category: "more" },
  { symbol: "MKR", name: "Maker", category: "more" },
  { symbol: "SNX", name: "Synthetix", category: "more" },
  { symbol: "CRV", name: "Curve DAO", category: "more" },
  { symbol: "YFI", name: "yearn.finance", category: "more" },
  { symbol: "BAT", name: "Basic Attention Token", category: "more" },
  { symbol: "ZRX", name: "0x Protocol", category: "more" },
  { symbol: "QTUM", name: "Qtum", category: "more" },
  { symbol: "ONT", name: "Ontology", category: "more" },
  { symbol: "IOST", name: "IOST", category: "more" },
  { symbol: "ICX", name: "ICON", category: "more" },
  { symbol: "WAVES", name: "Waves", category: "more" },
  { symbol: "KSM", name: "Kusama", category: "more" },
  { symbol: "FLOW", name: "Flow", category: "more" },
  { symbol: "CELO", name: "Celo", category: "more" },
  { symbol: "ROSE", name: "Oasis Network", category: "more" },
  { symbol: "ONE", name: "Harmony", category: "more" },
  { symbol: "ANKR", name: "Ankr", category: "more" },
  { symbol: "STORJ", name: "Storj", category: "more" },
  { symbol: "FET", name: "Fetch.ai", category: "more" },
  { symbol: "LDO", name: "Lido DAO", category: "more" },
  { symbol: "ENS", name: "Ethereum Name Service", category: "more" },
  { symbol: "MASK", name: "Mask Network", category: "more" },
  { symbol: "DYDX", name: "dYdX", category: "more" },
  { symbol: "GMX", name: "GMX", category: "more" },
  { symbol: "PYTH", name: "Pyth Network", category: "more" },
  { symbol: "JTO", name: "Jito", category: "more" },
  { symbol: "JUP", name: "Jupiter", category: "more" },
  { symbol: "WIF", name: "dogwifhat", category: "more" },
  { symbol: "BONK", name: "Bonk", category: "more" },
  { symbol: "FLOKI", name: "Floki", category: "more" },
  { symbol: "TRX", name: "TRON", category: "more" },
  { symbol: "NEO", name: "NEO", category: "more" },
  { symbol: "LUNC", name: "Terra Classic", category: "more" },
  { symbol: "APE", name: "ApeCoin", category: "more" },
  { symbol: "GMT", name: "STEPN", category: "more" },
  { symbol: "STX", name: "Stacks", category: "more" },
  { symbol: "ORDI", name: "ORDI", category: "more" },
  { symbol: "WLD", name: "Worldcoin", category: "more" },
  { symbol: "TON", name: "Toncoin", category: "more" },
  { symbol: "AR", name: "Arweave", category: "more" },
  { symbol: "RVN", name: "Ravencoin", category: "more" },
  { symbol: "ZIL", name: "Zilliqa", category: "more" },
  { symbol: "HOT", name: "Holo", category: "more" },
  { symbol: "WIN", name: "WINkLink", category: "more" },
  { symbol: "CVC", name: "Civic", category: "more" },
  { symbol: "KNC", name: "Kyber Network", category: "more" },
  { symbol: "BAND", name: "Band Protocol", category: "more" },
  { symbol: "LRC", name: "Loopring", category: "more" },
  { symbol: "BAL", name: "Balancer", category: "more" },
  { symbol: "NMR", name: "Numeraire", category: "more" },
  { symbol: "RLC", name: "iExec RLC", category: "more" },
  { symbol: "ANT", name: "Aragon", category: "more" },
  { symbol: "KDA", name: "Kadena", category: "more" },
  { symbol: "SXP", name: "Solar", category: "more" },
  { symbol: "C98", name: "Coin98", category: "more" },
  { symbol: "DYM", name: "Dymension", category: "more" },
  { symbol: "STRK", name: "Starknet", category: "more" },
  { symbol: "ALT", name: "AltLayer", category: "more" },
  { symbol: "PIXEL", name: "Pixels", category: "more" },
  { symbol: "PORTAL", name: "Portal", category: "more" },
  { symbol: "AEVO", name: "Aevo", category: "more" },
  { symbol: "ETHFI", name: "Ether.fi", category: "more" },
  { symbol: "ENA", name: "Ethena", category: "more" },
  { symbol: "W", name: "Wormhole", category: "more" },
  { symbol: "SAGA", name: "Saga", category: "more" },
  { symbol: "OMNI", name: "Omni Network", category: "more" },
  { symbol: "NOT", name: "Notcoin", category: "more" },
  { symbol: "RAY", name: "Raydium", category: "more" },
];

// Illustrative holdings for the sample portfolio view — quantities only,
// no purchase ever happens, priced against the real live tickers.
export type MockPortfolioHolding = {
  symbol: string;
  amount: number;
};

export const MOCK_HOLDINGS: MockPortfolioHolding[] = [
  { symbol: "BTC", amount: 0.42 },
  { symbol: "ETH", amount: 3.1 },
  { symbol: "SOL", amount: 25 },
  { symbol: "LINK", amount: 140 },
];

export const MOCK_CASH_BALANCE = 8250.5;
